site_name: Yoshi Docs

theme:
  name: material
  palette:
    scheme: slate  # This sets the default to dark mode
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - Home: index.md
  - Release Notes: index.md

  # GitHub Pages configuration
site_url: https://KiyoshiWasHere.github.io/Yoshi-Docs-Material